ALTER TABLE TODO ALTER COLUMN title VARCHAR NOT NULL;
ALTER TABLE TODO ALTER COLUMN done BOOLEAN NOT NULL;
ALTER TABLE TODO ALTER COLUMN created_at TIMESTAMP NOT NULL;
ALTER TABLE TODO ALTER COLUMN updated_at TIMESTAMP NOT NULL;