UPDATE TODO
SET
    title = ''
WHERE title IS NULL;

UPDATE TODO
SET
    done = false
WHERE done IS NULL;

ALTER TABLE TODO ALTER COLUMN title SET NOT NULL;
ALTER TABLE TODO ALTER COLUMN done SET NOT NULL;
ALTER TABLE TODO ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE TODO ALTER COLUMN updated_at SET NOT NULL;