DELETE FROM TODO WHERE TRUE;
ALTER TABLE TODO
    ADD COLUMN user_id BIGINT NOT NULL DEFAULT -1 AFTER id;
ALTER TABLE TODO
    ADD CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE ON UPDATE CASCADE;