ALTER TABLE TODO
    ADD COLUMN IF NOT EXISTS parent_id BIGINT;
ALTER TABLE TODO
    DROP CONSTRAINT IF EXISTS fk_parent;
ALTER TABLE TODO
    ADD CONSTRAINT fk_parent FOREIGN KEY (parent_id) REFERENCES TODO(id) ON DELETE CASCADE ON UPDATE CASCADE;